# Generated by Django 2.2.2 on 2020-01-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Bus_description',
        ),
    ]
