# Generated by Django 2.2.2 on 2020-01-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0002_auto_20200106_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_description',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
