# Generated by Django 2.2.2 on 2020-01-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0003_bus_description_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_description', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Buses.Bus_description')),
                ('seat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Buses.Seats')),
            ],
        ),
    ]
