# Generated by Django 2.2.2 on 2020-01-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0004_reservation_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_description',
            name='BusName',
            field=models.CharField(default='Lamjhung Travels', max_length=20),
        ),
        migrations.AddField(
            model_name='bus_description',
            name='images',
            field=models.ImageField(default='none', upload_to='pics'),
        ),
    ]
