# Generated by Django 2.2.2 on 2020-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0005_auto_20200108_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_description',
            name='images',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
