# Generated by Django 2.2.2 on 2020-01-08 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0006_auto_20200108_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 8, 23, 52, 43, 100446)),
        ),
    ]
