# Generated by Django 2.2.2 on 2020-01-11 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0007_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_description',
            name='dates',
            field=models.DateField(default=datetime.date(2020, 1, 11)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 15, 32, 25, 60515)),
        ),
    ]
