# Generated by Django 2.2.2 on 2020-01-11 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0008_auto_20200111_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_description',
            name='pick_destination',
            field=models.CharField(default='Gongabu Bus Park', max_length=30),
        ),
        migrations.AddField(
            model_name='bus_description',
            name='pick_time',
            field=models.TimeField(default=datetime.time(15, 38, 6, 324626)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 11, 15, 38, 6, 326607)),
        ),
    ]
