# Generated by Django 2.2.2 on 2020-01-12 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0009_auto_20200111_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_description',
            name='fare',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='bus_description',
            name='dates',
            field=models.DateField(default=datetime.date(2020, 1, 12)),
        ),
        migrations.AlterField(
            model_name='bus_description',
            name='pick_time',
            field=models.TimeField(default=datetime.time(23, 23, 12, 690378)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 12, 23, 23, 12, 690378)),
        ),
    ]
