# Generated by Django 2.2.2 on 2020-01-19 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0010_auto_20200112_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_description',
            name='dates',
            field=models.DateField(default=datetime.date(2020, 1, 19)),
        ),
        migrations.AlterField(
            model_name='bus_description',
            name='pick_time',
            field=models.TimeField(default=datetime.time(16, 22, 34, 626424)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 16, 22, 34, 626425)),
        ),
    ]
