# Generated by Django 2.2.2 on 2020-01-19 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0011_auto_20200119_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_description',
            name='pick_time',
            field=models.TimeField(default=datetime.time(16, 36, 0, 218541)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 16, 36, 0, 218541)),
        ),
    ]
