# Generated by Django 2.2.1 on 2020-02-10 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0014_auto_20200210_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_description',
            name='pick_time',
            field=models.TimeField(default=datetime.time(21, 21, 59, 977244)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 10, 21, 21, 59, 977245)),
        ),
    ]
